/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPalletInput: typeof import('./components/ColorPalletInput.vue')['default']
    Confirm: typeof import('./components/Confirm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistoryDisplay: typeof import('./components/HistoryDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreCountCard: typeof import('./components/ScoreCountCard.vue')['default']
  }
}
